import pygame
import random
import sys

# Initialize Pygame and mixer
pygame.init()
pygame.mixer.init()

# Load sound effects
attack_sound = pygame.mixer.Sound("attack.wav")
hit_sound = pygame.mixer.Sound("hit.wav")
heal_sound = pygame.mixer.Sound("heal.wav")

attack_sound.set_volume(1.0)
hit_sound.set_volume(1.0)
heal_sound.set_volume(1.0)

# Colors
WHITE = (255, 255, 255)
RED = (255, 50, 50)
GREEN = (50, 255, 50)
YELLOW = (255, 255, 50)
CYAN = (50, 255, 255)
BLACK = (0, 0, 0)

# Game window
WIDTH, HEIGHT = 800, 600
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Avengers Battle")
font = pygame.font.SysFont("consolas", 24)

# Directions
DIRECTION_NAMES = ["north", "east", "south", "west"]

# Rooms
HQ, NEW_YORK, WAKANDA, VILLAIN_LAIR = 0, 1, 2, 3

room_names = ["Avengers HQ", "New York City", "Wakanda", "Villain's Lair"]
room_descriptions = [
    "The Avengers HQ is buzzing with activity. Heroes gather here to plan.",
        "The streets of New York are chaotic with villains attacking civilians.",
            "Wakanda's advanced tech city glows with energy. Allies stand ready.",
                "The villain's lair is dark and full of traps. Danger lurks everywhere."
                ]
                room_objects = ["Mjolnir", "Shield", "Vibranium Suit", "Infinity Stone"]
                health_items = ["", "Medkit", "Healing Potion", ""]
                villain_hp = [-1, 30, 40, 100]

                connections = [
                    [NEW_YORK, WAKANDA, -1, -1],  # HQ
                        [-1, -1, HQ, -1],             # New York
                            [-1, VILLAIN_LAIR, -1, HQ],   # Wakanda
                                [-1, -1, -1, WAKANDA]         # Villain's Lair
                                ]

                                # Game state
                                current_room = HQ
                                player_hp = 100
                                inventory = []
                                running = True
                                log_lines = []

                                def add_log(text, color=WHITE):
                                    log_lines.append((text, color))
                                        if len(log_lines) > 20:
                                                log_lines.pop(0)

                                                def draw_screen():
                                                    screen.fill(BLACK)
                                                        y = 10
                                                            for line, color in log_lines:
                                                                    rendered = font.render(line, True, color)
                                                                            screen.blit(rendered, (10, y))
                                                                                    y += 30
                                                                                        pygame.display.flip()

                                                                                        add_log("Welcome to the Avengers Battle!", CYAN)

                                                                                        while running:
                                                                                            pygame.event.pump()  # keep Pygame responsive

                                                                                                # Show room info
                                                                                                    add_log(f"\nYou are in {room_names[current_room]}", YELLOW)
                                                                                                        add_log(room_descriptions[current_room])

                                                                                                            if room_objects[current_room]:
                                                                                                                    add_log(f"You see a {room_objects[current_room]} here.", GREEN)
                                                                                                                        if health_items[current_room]:
                                                                                                                                add_log(f"There is a {health_items[current_room]} here.", GREEN)

                                                                                                                                    # Exits
                                                                                                                                        exits = [DIRECTION_NAMES[i] for i, c in enumerate(connections[current_room]) if c != -1]
                                                                                                                                            add_log(f"Exits: {' '.join(exits)}", CYAN)

                                                                                                                                                # Villain encounter
                                                                                                                                                    if villain_hp[current_room] > 0:
                                                                                                                                                            add_log(f"A villain appears with {villain_hp[current_room]} HP!", RED)
                                                                                                                                                                    while villain_hp[current_room] > 0 and player_hp > 0:
                                                                                                                                                                                draw_screen()
                                                                                                                                                                                            pygame.time.delay(100)
                                                                                                                                                                                                        add_log(f"Your HP: {player_hp} | Villain HP: {villain_hp[current_room]}", YELLOW)
                                                                                                                                                                                                                    draw_screen()

                                                                                                                                                                                                                                # Get player input from console
                                                                                                                                                                                                                                            cmd = input("Do you want to 'attack', 'run', or 'use' a health item? ").lower()

                                                                                                                                                                                                                                                        if cmd == "attack":
                                                                                                                                                                                                                                                                        attack_sound.play()
                                                                                                                                                                                                                                                                                        player_damage = random.randint(5, 24)
                                                                                                                                                                                                                                                                                                        villain_damage = random.randint(5, 19)
                                                                                                                                                                                                                                                                                                                        if current_room == VILLAIN_LAIR:
                                                                                                                                                                                                                                                                                                                                            villain_damage += 10
                                                                                                                                                                                                                                                                                                                                                            if "Mjolnir" in inventory:
                                                                                                                                                                                                                                                                                                                                                                                player_damage += 10
                                                                                                                                                                                                                                                                                                                                                                                                if "Infinity Stone" in inventory:
                                                                                                                                                                                                                                                                                                                                                                                                                    player_damage += 20
                                                                                                                                                                                                                                                                                                                                                                                                                                    if "Shield" in inventory:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        villain_damage -= 5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if "Vibranium Suit" in inventory:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            villain_damage -= 10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            villain_damage = max(villain_damage, 0)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            villain_hp[current_room] -= player_damage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            add_log(f"You deal {player_damage} damage to the villain!", GREEN)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if villain_hp[current_room] > 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                hit_sound.play()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    player_hp -= villain_damage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        add_log(f"The villain hits back for {villain_damage} damage!", RED)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            add_log("You defeated the villain!", GREEN)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif cmd == "run":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        add_log("You retreat to the previous room.", CYAN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # move to a connected room (simplified)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for i, c in enumerate(connections[current_room]):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if c != -1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    current_room = c
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif cmd == "use":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if health_items[current_room]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            heal_sound.play()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                heal_amount = random.randint(20, 50)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    player_hp += heal_amount
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        add_log(f"You use the {health_items[current_room]} and recover {heal_amount} HP!", GREEN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            health_items[current_room] = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                add_log("No health items here!", RED)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            add_log("Unknown action.", RED)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if player_hp <= 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        add_log("You were defeated! Game over.", RED)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        running = False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    draw_screen()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not running:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Check win
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if all(hp <= 0 for hp in villain_hp):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        add_log("Congratulations! You defeated all villains and saved the world!", GREEN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                draw_screen()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Get player input for movement / actions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                draw_screen()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cmd = input("\nWhat do you do? ").lower()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if cmd in ["north", "n"] and connections[current_room][0] != -1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                current_room = connections[current_room][0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif cmd in ["east", "e"] and connections[current_room][1] != -1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            current_room = connections[current_room][1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif cmd in ["south", "s"] and connections[current_room][2] != -1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        current_room = connections[current_room][2]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif cmd in ["west", "w"] and connections[current_room][3] != -1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    current_room = connections[current_room][3]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif cmd == "look":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if room_objects[current_room]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            add_log(f"You inspect the {room_objects[current_room]}.", GREEN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif health_items[current_room]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                add_log(f"You inspect the {health_items[current_room]}.", GREEN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    add_log("There is nothing of interest here.", CYAN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif cmd == "take":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if room_objects[current_room]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            inventory.append(room_objects[current_room])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        add_log(f"You take the {room_objects[current_room]}.", GREEN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    room_objects[current_room] = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif health_items[current_room]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        inventory.append(health_items[current_room])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    add_log(f"You take the {health_items[current_room]}.", GREEN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                health_items[current_room] = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    add_log("There is nothing here to take.", RED)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif cmd in ["quit", "q"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                running = False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            add_log("Unknown command.", RED)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                draw_screen()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pygame.time.delay(100)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    add_log("Thanks for playing the Avengers Battle!", CYAN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    draw_screen()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pygame.time.delay(3000)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pygame.quit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sys.exit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    